# Generated by Django 4.2.30 on 2026-06-03 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_alter_category_options_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='status',
            field=models.CharField(choices=[(0, 'Draft'), (1, 'Published')], default='draft', max_length=20),
        ),
    ]
